name: "gliner_guard"
backend: "python"

max_batch_size: 64

dynamic_batching {
  preferred_batch_size: [ 1, 8, 16, 32, 64 ]
  max_queue_delay_microseconds: 50000
}

input [
  {
    name: "text"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

output [
  {
    name: "result"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
